function importApp() {
	var menu = {"groups":[{"id":"group1","levels":[{"id":"group1_level0","file":"level_0.json"},{"id":"group1_level1","file":"level_1.json"},{"id":"group1_level2","file":"level_2.json"},{"id":"group1_level3","file":"level_3.json"},{"id":"group1_level4","file":"level_4.json"}]},{"id":"group2","levels":[]},{"id":"group3","levels":[]}]};

	var group1_level0 = {"id":"group1_level0","buttons":[{"id":"btn1","shape":2},{"id":"btn2","shape":1}],"states":{"btn1":{"e1":"e1"},"btn2":{"e1":"e1"}},"stateMachine":{"e1":[{"event":"btn1","to":"e1","action":{"f":"createObsel","a":{"group":"btn1","color":5,"valence":0}}},{"event":"btn2","to":"e1","action":{"f":"createObsel","a":{"group":"btn2","color":2,"valence":1}}}],"initial":"e1"}};
	var group1_level1 = {"id":"group1_level1","buttons":[{"id":"btn1","shape":2},{"id":"btn2","shape":1},{"id":"btn3","shape":3}],"states":{"btn1":{"e1":"e1","e2":"e2"},"btn2":{"e1":"e1","e2":"e1"},"btn3":{"e1":"e1","e2":"e2"}},"stateMachine":{"e1":[{"event":"btn1","to":"e1","action":{"f":"createObsel","a":{"group":"btn1","color":3,"valence":-1}}},{"event":"btn2","to":"e2","action":{"f":"createObsel","a":{"group":"btn2","color":5,"valence":0}}},{"event":"btn3","to":"e1","action":{"f":"createObsel","a":{"group":"btn3","color":2,"valence":1}}}],"e2":[{"event":"btn1","to":"e2","action":{"f":"createObsel","a":{"group":"btn1","color":2,"valence":1}}},{"event":"btn2","to":"e1","action":{"f":"createObsel","a":{"group":"btn2","color":5,"valence":0}}},{"event":"btn3","to":"e2","action":{"f":"createObsel","a":{"group":"btn3","color":3,"valence":-1}}}],"initial":"e1"}};
	var group1_level2 = {"id":"group1_level2","buttons":[{"id":"btn1","shape":2},{"id":"btn2","shape":1}],"states":{"btn1":{"e1":"e1","e3":"e1","e2":"e2"},"btn2":{"e1":"e1","e2":"e1","e3":"e2"}},"stateMachine":{"e1":[{"event":"btn1","to":"e2","action":{"f":"createObsel","a":{"group":"btn1","color":2,"valence":1}}},{"event":"btn2","to":"e3","action":{"f":"createObsel","a":{"group":"btn2","color":2,"valence":1}}}],"e2":[{"event":"btn1","to":"e2","action":{"f":"createObsel","a":{"group":"btn1","color":3,"valence":-1}}},{"event":"btn2","to":"e3","action":{"f":"createObsel","a":{"group":"btn2","color":2,"valence":1}}}],"e3":[{"event":"btn1","to":"e2","action":{"f":"createObsel","a":{"group":"btn1","color":2,"valence":1}}},{"event":"btn2","to":"e3","action":{"f":"createObsel","a":{"group":"btn2","color":3,"valence":-1}}}],"initial":"e1"}};
	var group1_level3 = {"id":"group1_level3","buttons":[{"id":"btn1","shape":2},{"id":"btn2","shape":1},{"id":"btn3","shape":3}],"states":{"btn1":{"e1":"e1","e3":"e1","e2":"e2"},"btn2":{"e1":"e1","e2":"e1","e3":"e1"},"btn3":{"e1":"e1","e2":"e1","e3":"e2"}},"stateMachine":{"e1":[{"event":"btn1","to":"e2","action":{"f":"createObsel","a":{"group":"btn1","color":2,"valence":1}}},{"event":"btn2","to":"e1","action":{"f":"createObsel","a":{"group":"btn2","color":5,"valence":0}}},{"event":"btn3","to":"e3","action":{"f":"createObsel","a":{"group":"btn3","color":2,"valence":1}}}],"e2":[{"event":"btn1","to":"e2","action":{"f":"createObsel","a":{"group":"btn1","color":3,"valence":-1}}},{"event":"btn2","to":"e1","action":{"f":"createObsel","a":{"group":"btn2","color":5,"valence":0}}},{"event":"btn3","to":"e3","action":{"f":"createObsel","a":{"group":"btn3","color":2,"valence":1}}}],"e3":[{"event":"btn1","to":"e2","action":{"f":"createObsel","a":{"group":"btn1","color":2,"valence":1}}},{"event":"btn2","to":"e1","action":{"f":"createObsel","a":{"group":"btn2","color":5,"valence":0}}},{"event":"btn3","to":"e3","action":{"f":"createObsel","a":{"group":"btn3","color":3,"valence":-1}}}],"initial":"e1"}};
	var group1_level4 = {"id":"group1_level4","buttons":[{"id":"btn1","shape":1},{"id":"btn2","shape":1}],"states":{"btn1":{"e1":"e3","e2":"e2","e3":"e2","e4":"e1"},"btn2":{"e1":"e2","e2":"e1","e3":"e3","e4":"e2"}},"stateMachine":{"e1":[{"event":"btn1","to":"e1","action":{"f":"createObsel","a":{"group":"btn1","color":1,"valence":-4}}},{"event":"btn2","to":"e2","action":{"f":"createObsel","a":{"group":"btn2","color":1,"valence":-1}}}],"e2":[{"event":"btn1","to":"e4","action":{"f":"createObsel","a":{"group":"btn1","color":1,"valence":-1}}},{"event":"btn2","to":"e3","action":{"f":"createObsel","a":{"group":"btn2","color":1,"valence":3}}}],"e3":[{"event":"btn1","to":"e4","action":{"f":"createObsel","a":{"group":"btn1","color":1,"valence":-1}}},{"event":"btn2","to":"e3","action":{"f":"createObsel","a":{"group":"btn2","color":1,"valence":-4}}}],"e4":[{"event":"btn1","to":"e1","action":{"f":"createObsel","a":{"group":"btn1","color":1,"valence":3}}},{"event":"btn2","to":"e2","action":{"f":"createObsel","a":{"group":"btn2","color":1,"valence":-1}}}],"initial":"e1"}};

	storeObject({key: "menu", object: menu});

	storeObject({key: "group1_level0", object: group1_level0});
	storeObject({key: "group1_level1", object: group1_level1});
	storeObject({key: "group1_level2", object: group1_level2});
	storeObject({key: "group1_level3", object: group1_level3});
	storeObject({key: "group1_level4", object: group1_level4});
}
